import { Inter } from "next/font/google";
import "./globals.css";
import { CatIdProvider } from "@/provider/CatIdProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#ebeef2] relative`}>
        <CatIdProvider>{children}</CatIdProvider>
      </body>
    </html>
  );
};
export default RootLayout;
